name: MarketPlugin
main: se.jrp.marketplugin.MarketPlugin
version: 1
depend: [Vault]
commands:
   market:
      description: View the price of, sell or buy an item on the Market.
      usage: /market <sell:buy:price>
      permission:
      permission-message: