name: TestPlugin
main: se.jrp.testplugin.TestPlugin
version: 1
commands:
   test:
      description: A testing command.
      usage: /test [player] ...
      permission:
      permission-message: You don't have TestPlugin.test
   saplingwalk:
      description: Enables or disables saplingwalk.
      usage: /saplingwalk [enable/disable]
      permission:
      permission-message:
   bank:
      description: Get, store, send or view items in bank.
      usage: /bank [get, store, send, list]
      permission:
      permission-message:
  